<?php

########################################################################
# Extension Manager/Repository config file for ext: "freemind2"
#
# Auto generated by Extension Builder 2011-11-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FreeMind2',
	'description' => 'Exports your whole TYPO3 site or a branch as a .mm file for the favorite mind mapping tool FreeMind (http://freemind.sourceforge.net).
Adds items to the pagetree clickmenu to start the export of a branch. Or use the eID Param to use the link (with an API Key) directly in FreeMind.
Needs TYPO3 4.5 or later, SimpleXML, PHP5',
	'category' => 'be',
	'author' => 'Cyrill Schumacher',
	'author_email' => 'Cyrill@Schumacher.fm',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => '',
	'modify_tables' => 'pages,tt_content',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
